Alexander Gavruk. 09-redux
paralect/startupsummer2020 pull request #101
Opened 2020-07-16 21:03 UTC by KuzyaCat

2020-07-21 06:44 UTC, mikitasolo requested changes

2020-07-21 06:44 UTC, SobakaSlava commented on 09-redux/classworks/Gavruk_Alexander/src/components/SearchResults/SearchResults.css
> +.search-results {
cool class!

2020-07-21 06:44 UTC, SobakaSlava commented on 09-redux/classworks/Gavruk_Alexander/src/pages/Routes.js
> +function Routes(props) {
you don't need to get props here and pass farther anymore as you use Redux

2020-07-21 06:44 UTC, SobakaSlava commented on 09-redux/classworks/Gavruk_Alexander/src/resources/reducer.js
> +  ...reducers,
why do you create a new object?

2020-07-21 06:44 UTC, SobakaSlava commented on 09-redux/classworks/Gavruk_Alexander/src/pages/home/Home.js
> +    const data = await fetchReddit(url).then(res => res.json());
this logic should not be in component. it should be in action

2020-07-22 18:20 UTC, KuzyaCat commented on 09-redux/classworks/Gavruk_Alexander/src/components/SearchResults/SearchResults.css
> +.search-results {
@SobakaSlava ty

2020-07-28 09:20 UTC, SobakaSlava commented on 09-redux/classworks/Gavruk_Alexander/src/pages/Routes.js
> +        <Route path="/" exact component={() => <Home />} />
as we don't pass anything anymore we can make just `component={Home}`. but let's leave it as it is here

2020-07-28 09:21 UTC, mikitasolo approved these changes

2020-07-28 09:21 UTC, merged