Artem Chernov node
paralect/startupsummer2020 pull request #105
Opened 2020-07-17 11:19 UTC by metravonrech

2020-08-12 18:59 UTC, Oliferchik reviewed
А в целом красавчик, выглядит всё очень симпатиШно

2020-08-12 18:59 UTC, Oliferchik commented on 10-node/classworks/Artem_Chernov/index.js
> +  } else if (request.method === 'GET' && request.url === '/dir_name') {
Из-за наличия большого количество if возврастает цикломатическая сложность

В програмировании есть антипатерн с названием [Spaghetti code](https://en.wikipedia.org/wiki/Spaghetti_code), возникает он из-за увеличения цикломатической сложности.

Вместо if/else лучше использовать switch или объектные литералы. Вот [статейка](https://makeomatic.ru/blog/2014/12/17/Switch_statement/) на эту тему 

А вот [статейка](https://habr.com/ru/post/59005/) про анти-патерны, если будет желания почитать :)

2020-08-12 18:59 UTC, Oliferchik commented on 10-node/classworks/Artem_Chernov/index.js
> +  } else if (request.method === 'GET' && request.url === '/dir_name') {
Не плохо бы смотрелось, что-то на подобие :

```
const initGetRoutes = () => {
 switch (req.url) {
    case '/dir_name': console.log(__dirname);
    case '/file_name': console.log(__dirname+ '/home.html');
    case '/cpus': console.log(os.cpus());
    case '/number_of_cores': console.log(os.cpus().length);
    case '/home': ...
  }
}

const initPostRoutes = () => {
 ....
}


const routes = {
  get: initGetRoutes,
  post: initPostRoutes,
}

switch(req.method) {
    case 'GET': routes.get(),
    ...
}
```

2020-08-17 12:34 UTC, mikitasolo requested changes
Fix comments please

2020-08-18 11:58 UTC, mikitasolo approved these changes

2020-08-18 11:58 UTC, merged