add solution on task node
paralect/startupsummer2020 pull request #111
Opened 2020-07-17 12:00 UTC by kononovich11

2020-08-12 18:46 UTC, Oliferchik reviewed
А если в общем, молодчинка

2020-08-12 18:46 UTC, Oliferchik commented on 10-node/classworks/KononovichGalina/index.js
> +    if(key === '37e753db1079f7d8ff8d145769664df46b12d8c3a3c4930a2e66ab76a8bfb4ca9e0fe69b7bc40355755846342cf19c95c58fa538d964963f04aff409621ec330'){
лучше `37e753db1079f7d8ff8d145769664df46b12d8c3a3c4930a2e66ab76a8bfb4ca9e0fe69b7bc40355755846342cf19c95c58fa538d964963f04aff409621ec330` вынести в переменную, выглядит как [магическое число ](http://www.8bytes.net/2018/04/18/antipattern-1-magicheskoe-chislo/)

2020-08-12 18:46 UTC, Oliferchik commented on 10-node/classworks/KononovichGalina/index.js
> +  if(req.url === '/home') {
Вглядит как [Spaghetti code](https://en.wikipedia.org/wiki/Spaghetti_coder).

Мне кажется было бы лучше сделать что-то на подобие: 

```
const initGetRoutes = () => {
 switch (req.url) {
    case '/dir_name': console.log(__dirname);
    case '/file_name': console.log(__dirname+ '/home.html');
    case '/cpus': console.log(os.cpus());
    case '/number_of_cores': console.log(os.cpus().length);
    case '/home': ...
  }
}

const initPostRoutes = () => {
 ....
}


const routes = {
  get: initGetRoutes,
  post: initPostRoutes,
}

switch(req.method) {
    case 'GET': routes.get(),
    ...
}
```

2020-08-12 18:46 UTC, Oliferchik commented on 10-node/classworks/KononovichGalina/package.json
> +    "express": "^4.17.1",
Мы его не используем, можно удалить

2020-08-12 18:46 UTC, Oliferchik commented on 10-node/classworks/KononovichGalina/package.json
> +    "fs": "0.0.1-security",
Эти библиотеки вшиты в Node JS, их можно удалить.

2020-08-12 18:46 UTC, Oliferchik commented on 10-node/classworks/KononovichGalina/package.json
> +    "http": "0.0.1-security",
Эти библиотеки вшиты в Node JS, их можно удалить.

2020-08-12 18:46 UTC, Oliferchik commented on 10-node/classworks/KononovichGalina/package.json
> +    "nodemon": "^2.0.4",
не используй пожалуйста няшки :)

няшка, это ^

2020-08-17 12:20 UTC, mikitasolo requested changes
fix Sergey comments please

2020-08-19 10:25 UTC, SobakaSlava requested changes

2020-08-19 10:25 UTC, SobakaSlava commented on 10-node/classworks/KononovichGalina/index.js
> +      getHomePage(res);
please fix indentation of switch cases

2020-08-19 10:25 UTC, SobakaSlava commented on 10-node/classworks/KononovichGalina/index.js
> +      console.log(__dirname);
don't make it via console.log, better return it in body

2020-08-19 10:25 UTC, SobakaSlava commented on 10-node/classworks/KononovichGalina/index.js
> +    const key = crypto.pbkdf2Sync(req.headers.password , 'salt', 100000, 64, 'sha512').toString('hex') ;
why is password in headers? :confused:

2020-08-19 10:25 UTC, SobakaSlava commented on 10-node/classworks/KononovichGalina/index.js
> +    key === hash? res.write(JSON.stringify({ isValid: true })) : res.write(JSON.stringify({ isValid: false }));
better use if instead of ternary operator. you don't need returned value here

2020-08-27 08:30 UTC, merged