Volodkova Anna REST
paralect/startupsummer2020 pull request #130
Opened 2020-07-21 12:15 UTC by AnnaVolodkova

2020-08-02 09:08 UTC, KuhArt requested changes

2020-08-02 09:08 UTC, KuhArt commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    ctx.status = 200;
Я предлагаю вернуть статус 204. Он будет означать, что операция была выполнена успешно, однако в ответе сервера не содержится тела.

Вместо 'Okay!' можно вернуть пустой объект (`{}`)

2020-08-02 09:08 UTC, KuhArt commented on 12-rest/classworks/Volodkova_Anna/index.js
> +      ctx.status = 200;
Все же я предлагаю придерживаться более "гибкого" представления ответа сервера. Вместо отправки простых строк в теле ответа лучше отправлять js объект. Например, для 400 статуса вместо 'Incorrect login and password\n' будет `{ error: 'Incorrect login and password' }`,  а для 200 - вместо token будет `{token}`

2020-08-02 09:08 UTC, KuhArt commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    ctx.body = users;
К сожалению, поддержание промежуточного состояния сервиса в рантайме очень плохая практика. Лучше читать массив юзеров и тэгов при каждом новом запросе.

2020-08-02 09:08 UTC, KuhArt commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    ctx.body = 'All data received thank you';
Чаще всего результатом пост запроса является представление результата создания.
Поэтому я рекомендую дождаться результата ответа от стороннего сервиса, поместить результат в базу и после этого отправить js объект в ответе.

2020-08-05 09:21 UTC, AnnaVolodkova commented on 12-rest/classworks/Volodkova_Anna/index.js
> +      ctx.status = 200;
В слудющей строчке я переделала

2020-08-17 06:06 UTC, mikitasolo requested changes

2020-08-17 06:06 UTC, mikitasolo commented on 12-rest/classworks/Volodkova_Anna/index.js
> +const  fs = require('fs');
spaces

2020-08-17 06:06 UTC, mikitasolo commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    console.log('signUp body', ctx.request.body);
console.log

2020-08-17 06:06 UTC, mikitasolo commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    const passwordHash = myCripto(password);
`crypto`, not `cripto`
and anyway. bad name

2020-08-17 06:06 UTC, mikitasolo commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    users.push(userObj);
it will work only once. 
1. you read users from db
2. you add new user to the array
3. you write new array to the db
But after that
4. new user sends signup
5. you add him to the array (but old array)
6. you write it to the db and lose previous users

2020-08-17 06:06 UTC, SobakaSlava commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    const isLogIn = user.password === passwordHash;
why do we find user with such login and then check his password if we can do it at the same time

2020-08-17 06:06 UTC, SobakaSlava commented on 12-rest/classworks/Volodkova_Anna/index.js
> +    (async () => {
why do you create IIF?

2020-08-17 06:06 UTC, SobakaSlava commented on 12-rest/classworks/Volodkova_Anna/users.json
> +    "logIn": "Travis Ckott",
lol

2020-08-18 11:55 UTC, mikitasolo approved these changes

2020-08-18 11:57 UTC, merged