Alexander Gavruk. 12-rest
paralect/startupsummer2020 pull request #131
Opened 2020-07-21 21:18 UTC by KuzyaCat

2020-08-02 09:26 UTC, KuhArt submitted a review, later dismissed

2020-08-02 09:26 UTC, KuhArt commented on 12-rest/classworks/Gavruk_Alexander/server.js
> +  .get('/resources/user', async (ctx) => {
Слово `resources` можно исключить из строки запроса, т.к. оно не несет полезной нагрузки.

2020-08-02 09:26 UTC, KuhArt commented on 12-rest/classworks/Gavruk_Alexander/server.js
> +  .post('/write_resources/user', async (ctx) => {
Слово `write_resources` является избыточным в строке запроса. `POST` запрос уже говорит о том, что мы записываем ресурсы.

2020-08-02 09:26 UTC, KuhArt commented on 12-rest/classworks/Gavruk_Alexander/server.js
> +    ctx.body = JSON.parse(fs.readFileSync('./db/resources.json', 'utf8')).users;
Чаще всего результатом `POST` запроса является лишь представление объекта, созданного в ходе запроса.

2020-08-02 09:26 UTC, KuhArt commented on 12-rest/classworks/Gavruk_Alexander/server.js
> +    ctx.body = getResourcesDataFromDB();
Чаще всего результатом POST запроса является лишь представление объекта, созданного в ходе запроса.
Лучше вернуть только `article` в теле ответа.

2020-08-02 09:26 UTC, KuhArt commented on 12-rest/classworks/Gavruk_Alexander/server.js
> +    const tagline = await generateArticle(textPrompt).then(res => res.data.replies[0]);
Как я вижу для каждого запроса используется `generateArticle`. Если будет свободное время, то можно сделать три отдельных метода, соответствующих правилам задания. Однако, если есть более высока нагрузка на других заданиях, просто дай знать

2020-08-14 09:11 UTC, mikitasolo requested changes
remove not needed files from pr

2020-08-14 09:11 UTC, SobakaSlava commented on 12-rest/classworks/Gavruk_Alexander/server.js
> +    ctx.body = JSON.parse(fs.readFileSync('./db/resources.json', 'utf8')).users;
fix this comment

2020-08-18 11:43 UTC, mikitasolo submitted a review, later dismissed

2020-08-18 11:47 UTC, mikitasolo approved these changes

2020-08-18 11:48 UTC, merged