Vladimir Shevtsov 12 rest
paralect/startupsummer2020 pull request #146
Opened 2020-07-24 08:23 UTC by shevv920

2020-08-02 09:41 UTC, KuhArt requested changes

2020-08-02 09:41 UTC, KuhArt commented on 12-rest/classworks/Shevtsov_Vladimir/src/index.js
> +app.use(koaJwt({ secret: jwtSecret, passthrough: true, getToken }));
На сколько я понял, каждый запрос, приходящий на сервер, не  будет отклонен. При этом не важно, авторизованный он или нет. 
Я рекомендую совершить разделение на публичные и приватные роуты и убрать флажок `passthrough: true`. 
Про разделение роутов на публичные и приватные можешь поинтересоваться у ребят.

2020-08-02 09:41 UTC, KuhArt commented on 12-rest/classworks/Shevtsov_Vladimir/src/index.js
> +      ctx.status = 200;
Чаще всего в ответом `POST` запроса служит объект, созданный в ходе запроса. Я рекомендую добавить в тело ответа созданный объект (результат `generateFunc`).
Также, если не сложно, то добавь ключ `author` в новую сущность.

2020-08-14 09:03 UTC, mikitasolo requested changes

2020-08-14 09:03 UTC, SobakaSlava commented on 12-rest/classworks/Shevtsov_Vladimir/src/index.js
> +  users[name] = { pwdHash };
everyone can rewrite anyone :)

2020-08-14 09:03 UTC, mikitasolo approved these changes

2020-08-14 09:04 UTC, merged