Malkov 12-rest
paralect/startupsummer2020 pull request #147
Opened 2020-07-24 08:51 UTC by dzinrai

in progress

2020-08-02 10:38 UTC, KuhArt submitted a review, later dismissed

2020-08-02 10:38 UTC, KuhArt commented on 12-rest/classworks/Malkov_Alexei/index.js
> +  .get('/posts', async (ctx, next) => {
Для создания новых сущностей используют `POST` запрос.
Телом ответа должен быть объект, созданный в ходе запроса.

2020-08-02 10:38 UTC, KuhArt commented on 12-rest/classworks/Malkov_Alexei/index.js
> +      const decoded = jwt.verify(session.token, 'shhhhh');
Чтобы каждый раз не проверять токен, попробуй использовать пакет koa-jwt. 
Обратись за помощью ко мне или ребятам, если возникнут трудности.

2020-08-04 09:06 UTC, dzinrai commented on 12-rest/classworks/Malkov_Alexei/index.js
> +      const decoded = jwt.verify(session.token, 'shhhhh');
вроде подключил, разделил на публичные и приватные роуты

2020-08-14 08:58 UTC, mikitasolo requested changes

2020-08-14 08:58 UTC, SobakaSlava commented on 12-rest/classworks/Malkov_Alexei/checkUser.js
> +  let isExist = false;
no need to create this variable. just make multiple returns

2020-08-14 08:58 UTC, SobakaSlava commented on package.json
> +    "koa-jwt": "^4.0.0"
no comma

2020-08-17 07:34 UTC, mikitasolo submitted a review, later dismissed

2020-08-17 07:36 UTC, SobakaSlava commented
@dzinrai fix conflicts please

2020-08-17 11:17 UTC, mikitasolo approved these changes

2020-08-17 11:17 UTC, merged