GloriaLoi.12-rest
paralect/startupsummer2020 pull request #150
Opened 2020-07-25 18:44 UTC by gloooor

2020-08-02 10:14 UTC, KuhArt requested changes

2020-08-02 10:14 UTC, KuhArt commented on 12-rest/classworks/Gloria_Loi/index.js
> +      const tagline = [
Лучше хранить информацию в виде объекта. Например
```
{
author, // author name
text, // text result
}
```

2020-08-02 10:14 UTC, KuhArt commented on 12-rest/classworks/Gloria_Loi/index.js
> +          message: 'successfully posted',
В ответе чаще всего отправляется созданный объект.

2020-08-14 08:36 UTC, mikitasolo requested changes
Good job, I like it in general!

2020-08-14 08:36 UTC, mikitasolo commented on 12-rest/classworks/Gloria_Loi/database/tagline.json
> +  "AUTHOR NAME: 2 волк не лев шей-то посмотрел?",
но в цирке не выступает :point_up:

2020-08-14 08:36 UTC, mikitasolo commented on 12-rest/classworks/Gloria_Loi/index.js
> +const mySecret = 'super-mega-ochen-secret';
i like it

2020-08-14 08:36 UTC, mikitasolo commented on 12-rest/classworks/Gloria_Loi/index.js
> +    const pw = crypto
you use this func at least twice. it's a good point to make it a separate function

2020-08-14 08:36 UTC, mikitasolo commented on 12-rest/classworks/Gloria_Loi/index.js
> +    const pw = crypto
better name it passwordHash as it stores passwordHash

2020-08-14 08:36 UTC, mikitasolo commented on 12-rest/classworks/Gloria_Loi/index.js
> +      login,
i think we should not allow signing up with the same logins

2020-08-14 08:36 UTC, SobakaSlava commented on 12-rest/classworks/Gloria_Loi/index.js
> +let user;
it should not be a global variable. imagine someone is logging in and at this moment another user trie to log in and can rewrite this var. better create a user in every log in request

2020-08-14 08:36 UTC, SobakaSlava commented on 12-rest/classworks/Gloria_Loi/index.js
> +        autorName: user.login,
better replace by `author`

2020-08-14 08:36 UTC, SobakaSlava commented on 12-rest/classworks/Gloria_Loi/index.js
> +      const fetchData = await fetch('https://models.dobro.ai/gpt2/medium/', {
it would be nice if you make it a separate function as you write it multiple times

2020-08-26 09:44 UTC, SobakaSlava approved these changes

2020-08-26 09:46 UTC, SobakaSlava approved these changes

2020-08-26 09:46 UTC, merged