Ev rest
paralect/startupsummer2020 pull request #153
Opened 2020-07-30 06:06 UTC by Elaray1

2020-08-14 06:56 UTC, mikitasolo requested changes

2020-08-14 06:56 UTC, SobakaSlava commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +const privateRouter = router();
please stick to one style of variables naming

2020-08-14 06:56 UTC, SobakaSlava commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +  schema.validate(ctx.request.body);
how do you handle validation result?

2020-08-14 06:56 UTC, SobakaSlava commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +  if (db[ctx.request.body.login] === crypto.pbkdf2Sync(ctx.request.body.password, 'salt', 100000, 64, 'sha512').toString('hex')) {
you use this fn already second time. it's a good point to make a function for it

2020-08-14 06:56 UTC, SobakaSlava commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +privateRouter.post('/setdata/interview', async (ctx) => {
url should not have info about WHAT it does. but about WITH WHAT ENTITY it does. WHAT it does is described by the method

2020-08-14 06:56 UTC, SobakaSlava commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +    const info = await fetch('https://models.dobro.ai/gpt2/medium/', { method: 'POST', headers: { 'User-Agent': 'insomnia/2020.3.3' }, body: JSON.stringify({ prompt: el, length: 30, num_samples: 1 })
not readable

2020-08-14 06:56 UTC, SobakaSlava commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +    obj.tagline = { ...obj.tagline, el: info.replies[0] };
not sure it will work. you rewrite your el every time you make a request

2020-08-14 06:56 UTC, SobakaSlava commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +  db[ctx.request.body.login] = crypto.pbkdf2Sync(ctx.request.body.password, 'salt', 100000, 64, 'sha512').toString('hex');
users should be also stored in file db, not in JS object db as it will be lost after server restart

2020-08-16 17:52 UTC, Elaray1 commented on 12-rest/classworks/Egor_Emelyanov/index.js
> +privateRouter.post('/setdata/interview', async (ctx) => {
не кричи... тогда я ещё не знал...((((

2020-08-24 13:24 UTC, SobakaSlava approved these changes

2020-08-24 13:24 UTC, merged