Egor Emelyanov. Websockets
paralect/startupsummer2020 pull request #161
Opened 2020-08-03 15:38 UTC by Elaray1

2020-08-05 20:03 UTC, Ivanko5417 requested changes
Awesome!

2020-08-05 20:03 UTC, Ivanko5417 commented on 18-websockets/classworks/Emelyanov_Egor/example/server.js
> +
good endpoint! Could you please add comments a little bit here? It's hard to understand what is going on here because there is a lot of code.

2020-08-05 20:03 UTC, Ivanko5417 commented on 18-websockets/classworks/Emelyanov_Egor/example/server.js
> +    io.emit('message', { username: socket.username, message: msg });
I think it's not necessary to send 'message' event to everybody. You can send it to all users instead of current.

2020-08-05 20:03 UTC, Ivanko5417 commented on 18-websockets/classworks/Emelyanov_Egor/example/src/pages/Chat/Chat.jsx
> +    if (typingArr.findIndex((el) => el.username === username) === -1) {
let's move search user to the separate method

2020-08-05 20:03 UTC, Ivanko5417 commented on 18-websockets/classworks/Emelyanov_Egor/example/src/pages/Chat/Chat.jsx
> +      typingArr.splice(index, 1);
not sure that mutating this variable it's a good idea

2020-08-05 20:03 UTC, Ivanko5417 commented on 18-websockets/classworks/Emelyanov_Egor/example/src/pages/Chat/Chat.jsx
> +      const id = setTimeout(() => {
also, move please setting a timeout to separate method

2020-08-06 06:29 UTC, Elaray1 commented on 18-websockets/classworks/Emelyanov_Egor/example/server.js
> +
)0000))00000))))))

2020-08-06 08:11 UTC, Ivanko5417 approved these changes
:100:

2020-08-06 08:43 UTC, merged