Egor Emelyanov. React Native
paralect/startupsummer2020 pull request #164
Opened 2020-08-03 21:09 UTC by Elaray1

![image](https://user-images.githubusercontent.com/45394619/89227420-4ed50880-d5e6-11ea-8e6f-357740ab04f2.png)
![image](https://user-images.githubusercontent.com/45394619/89227431-55fc1680-d5e6-11ea-967e-93512a917bb0.png)
На макете у персонажей было реальное имя, в объекте с данными я такое поле не нашёл, а остальное вроде)) норм сделано

2020-08-05 10:05 UTC, mikitasolo requested changes

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/App.js
> +import { Provider } from "react-redux";
please remember to use single quotes in js

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/entity.selectors.js
> +export const getFavouritesCharacters = store => store.favouriteCharacters;
please check filename
also add empty line at the end of file (i recommend setting up your IDE to do it automatically)

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Details/Details.screen.js
> +    const { data } = await fetchMarvel(`/characters/${id}`);
HAHAHA, CAPS MAKES BLOP-BLOP-BLOP
NO FETCHING IN COMPONENT WHILE YOU HAVE REDUX IN YOUR APP

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Details/Details.screen.js
> +          &&
better place && next to `characterData`

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Details/Details.styles.js
> +    height: 170.56,
![image](https://user-images.githubusercontent.com/23057064/89396423-36184000-d717-11ea-8c3e-704188284d14.png)

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Details/Details.screen.js
> +  const { id, favouritesCharacters } = params;
better get favouritesCharacters by selector

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Details/Details.screen.js
> +  const { id, favouritesCharacters } = params;
though it's even better to pass `isFavourite` in params as you use `favouritesCharacters` only for getting info about if this character is favourite

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Favourites/Favourites.screen.js
> +                        style={styles.characterImg}
indentation

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Favourites/Favourites.screen.js
> +                        <Text style={styles.realName}>Egor Elaray</Text>
you're a superhero, man

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/MyMarvel/MyMarvel.screen.js
> +import { setfavouritesCharacters } from '../../store/actions/favouritesCharacters';
camel case

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/MyMarvel/MyMarvel.screen.js
> +import { setfavouritesCharacters } from '../../store/actions/favouritesCharacters';
and structure (actions inside entity, not entity inside actions)

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/MyMarvel/MyMarvel.screen.js
> +  const AddFavourite = (id, name, img) => {
wow, why `A` is big?

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/MyMarvel/MyMarvel.screen.js
> +                        style={styles.characterImg}
indentation

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/store/reducers/favouriteCharacters.js
> +        state.splice(index, 1);
better make filtering, don't use mutating functions

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/MyMarvel/MyMarvel.screen.js
> +            <View>
as I see the content of MyMarvel screen and Favourites.screen is the same except the array of data we map and render. it's a good idea to create a CharactersList component which will map and render provided Characters and we'll use it on MyMarvel.screen and Favourites.screen and provide different data

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Settings/Settings.screen.js
> +  const [isTrue, setIsTrue] = useState(false);
wat?

2020-08-05 10:05 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Settings/Settings.screen.js
> +function HomeScreen() {
Home? it's settings

2020-08-05 15:15 UTC, mikitasolo requested changes

2020-08-05 15:15 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/resources/characters/characters.actions.js
> +export const fetchCharacters = (fetchMarvel) => async dispatch => {
you don't need to receive props here. just import `fetchMarvel` directly in this file

2020-08-05 15:15 UTC, mikitasolo commented on 17-react-native/classworks/Emelyanov_Egor/task/resources/characters/characters.actions.js
> +    console.log('Cant get character data');
`Can't`

2020-08-05 15:15 UTC, SobakaSlava commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Details/Details.screen.js
> +            &&
.

2020-08-05 15:15 UTC, SobakaSlava commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Details/Details.screen.js
> +                      style={styles.comicsImg}
.

2020-08-05 15:15 UTC, SobakaSlava commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Favourites/Favourites.screen.js
> +                        style={styles.characterImg}
still

2020-08-05 15:15 UTC, SobakaSlava commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Favourites/Favourites.screen.js
> +            {favouritesCharacters.map(({ id, thumbnail, name, isFavourite }) => (
i told you to make a CharactersList component and reuse it instead of rewriting the same code twice

2020-08-05 15:15 UTC, SobakaSlava commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/Favourites/Favourites.screen.js
> +            &&
.

2020-08-05 15:15 UTC, SobakaSlava commented on 17-react-native/classworks/Emelyanov_Egor/task/resources/characters/characters.actions.js
> +    console.log('Cant get character data');
Can\'t

2020-08-05 18:50 UTC, Elaray1 commented
![image](https://user-images.githubusercontent.com/45394619/89452035-bc5b7300-d765-11ea-9ac0-67795be59db1.png)

2020-08-06 09:40 UTC, mikitasolo submitted a review, later dismissed

2020-08-06 09:40 UTC, SobakaSlava commented on 17-react-native/classworks/Emelyanov_Egor/task/screens/CharactersList/CharactersList.screen.js
> +import React from 'react';
it's not a screen. it's a usual component. the name of file and place where it's located should be different

2020-08-06 09:40 UTC, SobakaSlava commented
@Elaray1 please fix conflicts

2020-08-06 10:12 UTC, Elaray1 commented
@SobakaSlava who? (who?)

2020-08-06 10:24 UTC, mikitasolo submitted a review, later dismissed

2020-08-06 10:25 UTC, SobakaSlava commented
@Elaray1 
![image](https://user-images.githubusercontent.com/23057064/89521491-451af300-d7e8-11ea-8e06-e0209b5e3e41.png)

2020-08-06 10:55 UTC, mikitasolo submitted a review, later dismissed

2020-08-06 11:01 UTC, mikitasolo approved these changes

2020-08-06 11:01 UTC, merged