Vladimir Shevtsov. 17-react-native
paralect/startupsummer2020 pull request #170
Opened 2020-08-05 08:43 UTC by shevv920

2020-08-06 10:27 UTC, SobakaSlava commented
![image](https://user-images.githubusercontent.com/23057064/89521636-87dccb00-d7e8-11ea-8b58-a15bc1da7365.png)
wait what?

2020-08-06 10:28 UTC, SobakaSlava commented
i assume you should add `.expo` to the `.gitignore`

2020-08-06 10:31 UTC, SobakaSlava commented
> ![image](https://user-images.githubusercontent.com/23057064/89521636-87dccb00-d7e8-11ea-8b58-a15bc1da7365.png)
> wait what?

2020-08-13 11:44 UTC, mikitasolo requested changes

2020-08-13 11:44 UTC, mikitasolo commented on 17-react-native/classworks/Shevtsov_Vladimir/task/App.js
> +const  App = () => {
why 2 spaces?

2020-08-13 11:44 UTC, mikitasolo commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.action.js
> +const fetchComicsStart = () => ({ type: FETCH_COMICS_START });
for what?

2020-08-13 11:44 UTC, mikitasolo commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.action.js
> +export const addToFavorites = (obj) => ({ type: ADD_CHARACTER_TO_FAVORITES, payload: obj });
this 2 actions can be united into the one

2020-08-13 11:44 UTC, mikitasolo commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.reducer.js
> +  fetching: false,
i don't see `data` in initialState, please add

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.reducer.js
> +      return { ...state, favorites: uniqBy([...state.favorites, action.payload], 'id') };
no need to store favorites separately. it's better to use flags like `isFavorite`

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.selector.js
> +export const getFetching = (state) => state.comics.fetching;
```suggestion
export const getIsFetching = (state) => state.comics.isFetching;
```

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.selector.js
> +  const chars = uniqBy(results, "id").map((obj) => (
why uniqBy? what is the situation when we have items with the same id in results?

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.selector.js
> +export const getData = (state) => state.comics.data;
```suggestion
export const getComics = (state) => state.comics.data;
```

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.action.js
> +export const fetchCharacters = () => (dispatch) => {
why is this in `comics.actions.js`?

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.reducer.js
> +      console.log(payload.data);
.

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.reducer.js
> +      const chars = [...state.characters.filter((c) => c.id !== payload.characterId), char];
the order of chars will change after every fetching of comics. it's not good.

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/resources/comics.reducer.js
> +        characters: uniqBy(action.payload, "id").map((obj) => (
what is the situation when we have items with the same id?

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/screens/Details/Details.screen.js
> +  const isFavorite = favorites.find((char) => char.id === character.id);
this should be a selector

2020-08-13 11:44 UTC, SobakaSlava commented on 17-react-native/classworks/Shevtsov_Vladimir/task/screens/Favourite/Favourite.screen.js
> +import { removeFromFavorites } from '../../resources/comics.action';
the file should be named `comics.actions`

2020-08-17 07:20 UTC, mikitasolo approved these changes

2020-08-17 07:20 UTC, merged