Kononovich Galina html/css part2
paralect/startupsummer2020 pull request #37
Opened 2020-07-09 10:06 UTC by kononovich11

2020-07-10 11:34 UTC, aleksays requested changes

2020-07-10 11:34 UTC, aleksays commented on 03-html-css-part-2/Kononovich_Galina/contacts.html
> +            <div class="aContainer">
Супер стремное название класса)))

2020-07-10 11:34 UTC, aleksays commented on 03-html-css-part-2/Kononovich_Galina/contacts.html
> +        <div class="containerContacts">
Не обязательно добавлять `container` в названии класса 😄. Вполне достаточно `.contacts`

2020-08-18 13:38 UTC, mikitasolo approved these changes

2020-08-18 13:38 UTC, merged