Pk 03 html css part 2
paralect/startupsummer2020 pull request #38
Opened 2020-07-09 10:57 UTC by ZZireal

2020-07-10 11:30 UTC, aleksays requested changes

2020-07-10 11:30 UTC, aleksays commented on 02-html-css-part-1/classworks/Podgornaya_Katerina/home.html
> +            <div class='navMenuItem' id='activeMenuItem'><a href='home.html'>
Вместо `id="activeMenuItem"` лучше использовать дополнительный класс-модификатор `class="navMenuItem navMenuItem--active"`. Помни о specificity, у id слишком большой вес среди селекторов

2020-07-10 11:30 UTC, aleksays commented on 02-html-css-part-1/classworks/Podgornaya_Katerina/style.css
> +  src: url(fonts/SourceSansPro-Light.ttf);
В реальном проекте .ttf недостаточно. Нужно генерить веб шрифты. В этом тебе помогут онлайн генераторы шрифтов. Например я использую [fontsquirrel]( https://www.fontsquirrel.com/tools/webfont-generator)

2020-07-10 11:30 UTC, aleksays commented on 02-html-css-part-1/classworks/Podgornaya_Katerina/style.css
> +  flex-direction: row;
`flex-direction: row` - лишнее в данном случае. Значение row по умолчанию

2020-07-10 11:30 UTC, aleksays commented on 02-html-css-part-1/classworks/Podgornaya_Katerina/style.css
> +.navMenuItem a {
Вместо каскада лучше класс. То есть вместо этого `.navMenuItem a {` вот это - `.navMenuItem__link`

2020-07-10 11:30 UTC, aleksays commented on 02-html-css-part-1/classworks/Podgornaya_Katerina/style.css
> +  grid-template-columns: 20% 20% 20% 20% 20%;
Не совсем понял что тут происходит 😄. Зачем два раза одно свойство с разными значениями?)
В любом случае, если размеры элемента сетки одинаковые используй функцию `repeat(4, 25%) / repeat(4, 1fr)`

2020-07-10 11:30 UTC, aleksays commented on 03-html-css-part-2/contacts.html
> +<footer></footer>
а на мокапе был футер?)))

2020-07-10 11:30 UTC, aleksays commented on 03-html-css-part-2/home.html
> +                <header class='nav-logo-caption'>
Если используешь БЭМ, нужно визуально отделять имя элемента блока и модификатора, советую заглянуть в документацию по использованию БЭМ. 
Я использую такой вид - `block__element--modificator`. Вариантов много, гугл в помощь, но этот встречается чаще.
В данном случае правильно будет так - `nav__logo` (хотя logo я бы сделал отдельным блоком, так как он может использоваться и других местах), `nav__logo-icon, nav__logo-caption`

2020-07-10 11:30 UTC, aleksays commented on 03-html-css-part-2/home.html
> +<footer></footer>
Empty footer again)))

2020-07-10 11:30 UTC, aleksays commented on 03-html-css-part-2/styles/common_adaptive_style.css
> +    font-size: 3vw;
Не совсем уверен, единицы измерения `vw` подходят для `font-size`. Если хочешь использовать относительные единицы измерения - используй **rem**

2020-08-08 12:05 UTC, ZZireal commented on 02-html-css-part-1/classworks/Podgornaya_Katerina/style.css
> +  grid-template-columns: 20% 20% 20% 20% 20%;
:D
когда делала первую таску, то как-то с grid-ами совсем плохо было и скопировала откуда-то не разбираясь (
во второй таске уже решила полностью все переделать с нуля, чтобы получше структуру сделать и понимать все, что пишу

2020-08-08 12:05 UTC, ZZireal commented on 03-html-css-part-2/contacts.html
> +<footer></footer>
привыкла сначала писать шапку, тело и подвал)00
забыла удалить

2020-08-18 13:40 UTC, mikitasolo requested changes
leave only files related to htmls css part 2

2020-08-19 09:22 UTC, SobakaSlava approved these changes

2020-08-19 09:22 UTC, merged