pogudo tatyana . html/css part2
paralect/startupsummer2020 pull request #47
Opened 2020-07-09 13:42 UTC by PogudoTanya

2020-07-10 10:59 UTC, aleksays requested changes

2020-07-10 10:59 UTC, aleksays commented on 03-html-css-part-2/classworks/Pogudo_Tanya/style.css
> +.body__grid-first,
1. Хватит одного селектора, для 5 селекторов одинаковые стили, нет никакого смысла. Используй один селектор, например `.body__grid or .body__grid-item`
2. Классы с названием типа first, second, third - антипаттерн, не стоит их использовать, тем более в таком контексте как у тебя. Если нужно задать элементу списка стили которые отличаются от всех остальных элементов - используй псевдо селекторы `&:first-child, &:last-child, &:nth-child() etc.`

2020-07-10 10:59 UTC, aleksays commented on 03-html-css-part-2/classworks/Pogudo_Tanya/style.css
> +li {
Вроде договаривались что будем использовать БЭМ, а тут селектор тега, а дальше каскад)))

2020-08-18 13:41 UTC, mikitasolo requested changes
please fix comments

2020-08-26 08:11 UTC, merged