Gl 02 html css part 1
paralect/startupsummer2020 pull request #52
Opened 2020-07-10 08:02 UTC by gloooor

2020-07-10 11:07 UTC, aleksays requested changes

2020-07-10 11:07 UTC, aleksays commented on 02-html-css-part-1/classworks/Loi_Gloria/styles/common.css
> +@import url("https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap");
Если используешь CDN для шрифтов, лучше подключать их через `<link>`  в html документе - загрузка будет быстрее

2020-07-10 11:07 UTC, aleksays commented on 02-html-css-part-1/classworks/Loi_Gloria/styles/home.css
> +.first-title {
Когда в названии класса есть first, second, third etc - это плохо, это антипаттерн, тем более класс `.second-title` я не нашел :) Используй более говорящее название, например - `.main-title, .title, .block-title, .page-title` etc.

2020-08-18 13:42 UTC, mikitasolo requested changes
fix conflicts

2020-08-26 08:38 UTC, merged