Egor Emelyanov. React-1
paralect/startupsummer2020 pull request #81
Opened 2020-07-14 13:15 UTC by Elaray1

2020-07-29 13:19 UTC, mikitasolo requested changes

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/Routes.js
> +        <Route path="/" exact component={() => <Home />} />
no need of () => <Home /> as we don't pass props from here anymore

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/Routes.js
> +        <Route path="/subreddit/:subredditUrl" component={(props) => <Home {...props} />} />
and here

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/header/Header.js
> +import { setInputValueAction } from "../../store/actions/inputValue";
unary quotes in js

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/header/Header.js
> +    setInputVal(e.target.value);
you must not have 2 sources of truth. either state or redux

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +
no need of this empty line

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +  const [reactSubreddit, setReactSubreddit] = useState(null);
again 2 sources of truth

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +  const getInputValue = store => store.inputValue;
move selectors to separate `entity.selectors.js` file

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +      if (!props.location) {
the logic in `if` and `else` blocks is the same. the only difference is the URL. no need to split the logic in this way

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +import fuckImg from './fuck.jpg';
i don't like it (and Misha too)

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +        <p className="search-results-p">Search results for “ <span className="fw-b">{ inputValue }</span> ”</p>
```suggestion
        <p className="search-results-p">
            Search results for “ 
            <span className="fw-b">{inputValue}</span>
            ”
        </p>
```

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +            <div className="chiki-bamboni">
nah :madagascar:

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +      {reactSubreddit.data && Object.keys(reactSubreddit).length !== 0 && reactSubreddit.data.children.length ?
`true && true` ?

2020-07-29 13:19 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +        !props.location ?
double ternary operator is banned

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/Routes.js
> +function Routes({ inputValue }) {
you don't need it anymore

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/header/Header.js
> +import { setInputValueAction } from "../../store/actions/inputValue";
just `setInputValue`, without word `Action`

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +import moment from "moment";
the order of imports:
1. libraries
2. absolute imports
3. relative imports

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +        data = await fetchReddit(`/search?q=${inputValue}&type=sr,user`)
component should not call fetch. component should only dispatch

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +  const notFound = () => {
1 file = 1 component.

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +        <p>Sorry, there were no community results for “ {inputValue} ”</p>
why spaces around `inputValue`?

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +        <ul>
multiple indentation errors in this file

2020-07-29 13:19 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/store/actions/inputValue.js
> +export const SET_INPUT_VALUE = "SET_INPUT_VALUE";
single quotes

2020-07-29 14:14 UTC, Elaray1 commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +import fuckImg from './fuck.jpg';
Do u line Lukashekno? (And Misha?)

2020-07-29 14:15 UTC, Elaray1 commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +import fuckImg from './fuck.jpg';
like*

2020-08-04 08:34 UTC, mikitasolo requested changes
please make good code

2020-08-04 08:34 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/entity.selectors.js
> +export const getInputValue = store => store.inputValue;
`entity.selectors.js` was an example of file name, where `entity` is a placeholder

2020-08-04 08:34 UTC, mikitasolo commented on 07-react-1/classworks/Emelyanov_Egor/src/entity.selectors.js
> +export const getInputValue = store => store.inputValue;
you should have separate `*.selectors.js` file for every entity in your app. also it should be not in `src` folder bit in `resources`. use `koa-react-starter` as a reference please

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/Routes.js
> +        <Route path="/subreddit/:subredditUrl" component={(props) => <Home {...props} />} />
why no changes here for that comment?

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/CommunityList.js
> +          <div className="community-info">
indentation is broken

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/CommunityPosts.js
> +import lukashenkoImg from './lukashenko.jpg';
`lukashenko.jpg` here but `lukasenko.jpg` in another file

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +import { useDispatch } from 'react-redux';
one library - one line

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +    async function fetchData() {
NO FETCHING IN COMPONENTS. COMPONENTS ONLY DO RENDERS AND DISPATCHS

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/Home.js
> +            <div className="community-info">
indentation is broken

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/getSubredditInfo.js
> +import { setSubredditData } from '../../store/actions/subredditData';
`getSubredditInfo` should be in `entity.actions.js` file. the structure should be:
![image](https://user-images.githubusercontent.com/23057064/89271622-a35ba080-d645-11ea-9965-6780ee1cc43c.png)

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/pages/home/CommunityPosts.js
> +import lukashenkoImg from './lukashenko.jpg';
while filename is 
![image](https://user-images.githubusercontent.com/23057064/89271699-bc645180-d645-11ea-9af7-80eaa5636a2f.png)

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/store/reducers/index.js
> +  inputValue,
i doubt you should create a reducer for one string. better name it `input` and it will be the object { value: '' }

2020-08-04 08:34 UTC, SobakaSlava commented on 07-react-1/classworks/Emelyanov_Egor/src/style.css
> +.community-info {
lol, why all styles in one css? not goood

2020-08-04 08:34 UTC, SobakaSlava commented on package.json
> +    "redux-thunk": "^2.3.0"
why installing in global package.json?

2020-08-05 08:20 UTC, mikitasolo approved these changes

2020-08-05 08:20 UTC, merged